#ifndef SDA_PLATFORM_CONSTS_H
#define SDA_PLATFORM_CONSTS_H

// Constants

#define MIN_VOLTAGE 3.1
#define MAX_VOLTAGE 4.0
#define BATT_ADC_CONST_DEF 0.0013657
#define VOLTAGE_REF_VAL_DEF 0.626

// Pin & Port defs

#define SDA_BASE_BTN_PWR_PIN  GPIO_PIN_0
#define SDA_BASE_BTN_PWR_PORT GPIOA

#define SDA_BASE_SYSLED_PORT GPIOB
#define SDA_BASE_SYSLED_PIN  GPIO_PIN_2

#define SDA_BASE_SPEAKER_PORT GPIOA
#define SDA_BASE_SPEAKER_PIN  GPIO_PIN_4

#define SDA_BASE_BTN_A_PIN  GPIO_PIN_0
#define SDA_BASE_BTN_A_PORT GPIOE

#define SDA_BASE_BTN_LEFT_PIN  GPIO_PIN_2
#define SDA_BASE_BTN_LEFT_PORT GPIOE

#define SDA_BASE_BTN_UP_PIN  GPIO_PIN_5
#define SDA_BASE_BTN_UP_PORT GPIOE

#define SDA_BASE_BTN_DOWN_PIN  GPIO_PIN_4
#define SDA_BASE_BTN_DOWN_PORT GPIOE

#define SDA_BASE_BTN_RIGHT_PIN  GPIO_PIN_3
#define SDA_BASE_BTN_RIGHT_PORT GPIOE

#define SDA_BASE_BTN_B_PIN  GPIO_PIN_1
#define SDA_BASE_BTN_B_PORT GPIOE

#define SDA_BASE_PIN_IN  0
#define SDA_BASE_PIN_OUT 1
#define SDA_BASE_PIN_ALT 2

#define SDA_BASE_PIN_NOPULL   0
#define SDA_BASE_PIN_PULLDOWN 1
#define SDA_BASE_PIN_PULLUP   2


// ======= Supported Features =============

//#define SDA_FEATURE_NOTIF_VIBRO
//#define SDA_FEATURE_AMB_LIGHT_SENS
//#define SDA_FEATURE_IEXP_V2
//#define SDA_FEATURE_PCM_SOUND
#define SDA_FEATURE_EEXP_V1
//#define SDA_FEATURE_FREQ_SCALING

//#define MIN_PCM_VOLUME_VALUE 500
//#define MAX_PCM_VOLUME_VALUE 46000

//#define MIN_PCM_VOLUME_PHONES 100
//#define MAX_PCM_VOLUME_PHONES 8000

// ======== SVS overrides =================

//#define STRING_FIELD_L 64000
//#define TOKEN_SEGMENT_SIZE 256

#endif
